"use strict";

/** @type {import('sequelize-cli').Migration} */
module.exports = {
  async up(queryInterface, Sequelize) {
    await queryInterface.bulkInsert(
      "Productos",
      [
        {
          producto: "TAZA",
          tipo: "VIDRIO NO SUBLIMABLE",
          color: "",
          cantidad: 9,
          precio: 0,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          producto: "TAZA",
          tipo: "TRADICIONAL",
          color: "BLANCA",
          cantidad: 42,
          precio: 0,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          producto: "TAZA",
          tipo: "FONDO ROJO",
          color: "BLANCA",
          cantidad: 0,
          precio: 0,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          producto: "TAZA",
          tipo: "SIMULACION DE PELTRE",
          color: "",
          cantidad: 8,
          precio: 0,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          producto: "TAZA",
          tipo: "PELTRE REAL",
          color: "",
          cantidad: 1,
          precio: 0,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          producto: "TAZA",
          tipo: "CUCHI 6OZ",
          color: "",
          cantidad: 2,
          precio: 0,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          producto: "TAZA",
          tipo: "METALIZADAS",
          color: "DORADA",
          cantidad: 6,
          precio: 0,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          producto: "TAZA",
          tipo: "METALIZADAS",
          color: "PLATEADAS",
          cantidad: 12,
          precio: 0,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          producto: "TAZA",
          tipo: "METALIZADAS",
          color: "AZUL",
          cantidad: 0,
          precio: 0,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          producto: "TAZA",
          tipo: "METALIZADAS",
          color: "ROSADA",
          cantidad: 0,
          precio: 0,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          producto: "TAZA",
          tipo: "METALIZADAS",
          color: "ROSE GOLD",
          cantidad: 10,
          precio: 0,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          producto: "TAZA",
          tipo: "METALIZADAS",
          color: "VERDE",
          cantidad: 5,
          precio: 0,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          producto: "TAZA",
          tipo: "METALIZADAS",
          color: "PLOMO",
          cantidad: 9,
          precio: 0,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          producto: "TAZA",
          tipo: "PERLADAS",
          color: "ROSADA",
          cantidad: 6,
          precio: 0,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          producto: "TAZA",
          tipo: "PERLADAS",
          color: "BLANCA",
          cantidad: 0,
          precio: 0,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          producto: "TAZA",
          tipo: "PERLADAS",
          color: "GRIS",
          cantidad: 2,
          precio: 0,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          producto: "TAZA",
          tipo: "PERLADAS",
          color: "FUCSIA",
          cantidad: 5,
          precio: 0,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          producto: "TAZA",
          tipo: "MÁGICA FONDO BLANCO",
          color: "MATTE",
          cantidad: 12,
          precio: 0,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          producto: "TAZA",
          tipo: "MÁGICA FONDO ROJO",
          color: "MATTE",
          cantidad: 3,
          precio: 0,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          producto: "TAZA",
          tipo: "MÁGICA FONDO AZUL",
          color: "MATTE",
          cantidad: 11,
          precio: 0,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          producto: "TAZA",
          tipo: "MÁGICA FONDO ROSA",
          color: "MATTE",
          cantidad: 12,
          precio: 0,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          producto: "TAZA",
          tipo: "MÁGICA FONDO BLANCO",
          color: "ESCARCHADA",
          cantidad: 14,
          precio: 0,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          producto: "TAZA",
          tipo: "NEÓN",
          color: "NARANJA",
          cantidad: 3,
          precio: 0,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          producto: "TAZA",
          tipo: "NEÓN",
          color: "VERDE",
          cantidad: 5,
          precio: 0,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          producto: "TAZA",
          tipo: "NEÓN",
          color: "FUCSIA",
          cantidad: 5,
          precio: 0,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          producto: "TAZA",
          tipo: "NEÓN",
          color: "AMARILLO",
          cantidad: 4,
          precio: 0,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          producto: "TAZA",
          tipo: "CÓNICA 12 OZ",
          color: "",
          cantidad: 5,
          precio: 0,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          producto: "TAZA",
          tipo: "CÓNICA 17 OZ",
          color: "",
          cantidad: 5,
          precio: 0,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          producto: "TAZA",
          tipo: "VASO CONICO CON TAPA SILICONE",
          color: "",
          cantidad: 4,
          precio: 0,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          producto: "JARRA",
          tipo: "CERVECERA TRANSPARENTE",
          color: "",
          cantidad: 11,
          precio: 0,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          producto: "JARRA",
          tipo: "CERVECERA FONDO ROJO",
          color: "",
          cantidad: 1,
          precio: 0,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          producto: "JARRA",
          tipo: "CERVECERA FONDO VERDE",
          color: "",
          cantidad: 0,
          precio: 0,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          producto: "TERMO",
          tipo: "VASO ALUMIONIO C/TAPA NO SUBLIMABLE",
          color: "",
          cantidad: 10,
          precio: 0,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          producto: "TERMO",
          tipo: "LECHERO",
          color: "PLATEADO",
          cantidad: 2,
          precio: 0,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          producto: "TERMO",
          tipo: "LECHERO",
          color: "BLANCO",
          cantidad: 2,
          precio: 0,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          producto: "TERMO",
          tipo: "LATA ALUMINIO TIPO REFRESCO",
          color: "",
          cantidad: 2,
          precio: 0,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          producto: "TERMO",
          tipo: "VASO VINERO SUBLIMABLE",
          color: "",
          cantidad: 0,
          precio: 0,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          producto: "TERMO",
          tipo: "MASON JAR CON TAPA Y PITILLO",
          color: "",
          cantidad: 1,
          precio: 0,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          producto: "TERMO",
          tipo: "BOTELLITA ALUMINIO",
          color: "",
          cantidad: 0,
          precio: 0,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          producto: "TERMO",
          tipo: "DEP. BLANCO C/PILLITO",
          color: "NEGRO",
          cantidad: 1,
          precio: 0,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          producto: "TERMO",
          tipo: "C/TAPA ROSCA",
          color: "NARANJA",
          cantidad: 8,
          precio: 0,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          producto: "TERMO",
          tipo: "C/TAPA ROSCA",
          color: "GRIS",
          cantidad: 0,
          precio: 0,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          producto: "TERMO",
          tipo: "DEP. ROSCA CON LAVERO",
          color: "VERDE",
          cantidad: 10,
          precio: 0,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          producto: "TERMO",
          tipo: "DEP. ROSCA CON LAVERO",
          color: "AZUL",
          cantidad: 2,
          precio: 0,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          producto: "TERMO",
          tipo: "ALUMINIO",
          color: "BLANCA",
          cantidad: 10,
          precio: 0,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          producto: "TERMO",
          tipo: "ALUMINIO SUBLIMABLE",
          color: "BLANCA",
          cantidad: 1,
          precio: 0,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          producto: "TAZA",
          tipo: "GLASEADA TRANSPARENTE",
          color: "",
          cantidad: 6,
          precio: 0,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          producto: "TAZA",
          tipo: "GLASEADA FONDO VERDE",
          color: "",
          cantidad: 6,
          precio: 0,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          producto: "TAZA",
          tipo: "GLASEADA FONDO ROJO",
          color: "",
          cantidad: 5,
          precio: 0,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          producto: "TAZA",
          tipo: "GLASEADA FONDO ROSADO",
          color: "",
          cantidad: 6,
          precio: 0,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          producto: "TAZA",
          tipo: "GLASEADA FONDO AZUL",
          color: "",
          cantidad: 3,
          precio: 0,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          producto: "TAZA",
          tipo: "GLASEADA PORTA VASOS SUBLIMABLE",
          color: "",
          cantidad: 9,
          precio: 0,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          producto: "LLAVERO",
          tipo: "RECTANGULAR",
          color: "PLATEADO",
          cantidad: 1,
          precio: 0,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          producto: "LLAVERO",
          tipo: "RECTANGULAR",
          color: "BLANCO",
          cantidad: 0,
          precio: 0,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          producto: "LLAVERO",
          tipo: "CUADRADO",
          color: "PLATEADO",
          cantidad: 0,
          precio: 0,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          producto: "LLAVERO",
          tipo: "REDONDO",
          color: "PLATEADO",
          cantidad: 11,
          precio: 0,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          producto: "LLAVERO",
          tipo: "CORAZON",
          color: "BLANCO",
          cantidad: 0,
          precio: 0,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          producto: "LLAVERO",
          tipo: "CORAZON",
          color: "PLATEADO",
          cantidad: 0,
          precio: 0,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          producto: "LLAVERO",
          tipo: "HUESO",
          color: "",
          cantidad: 1,
          precio: 0,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          producto: "LLAVERO",
          tipo: "TABLA SURF",
          color: "COLOR",
          cantidad: 32,
          precio: 0,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          producto: "LLAVERO",
          tipo: "ARBOL NAVIDAD",
          color: "",
          cantidad: 10,
          precio: 0,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          producto: "DESTAPADOR",
          tipo: "BOTELLA",
          color: "PLATEADO",
          cantidad: 2,
          precio: 0,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          producto: "DESTAPADOR",
          tipo: "BOTELLA",
          color: "BLANCO",
          cantidad: 0,
          precio: 0,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          producto: "DESTAPADOR",
          tipo: "CERVEZA",
          color: "PLATEADO",
          cantidad: 3,
          precio: 0,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          producto: "DESTAPADOR",
          tipo: "CERVEZA",
          color: "BLANCO",
          cantidad: 5,
          precio: 0,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          producto: "LAPICERO",
          tipo: "",
          color: "",
          cantidad: 0,
          precio: 0,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
      ],
      {}
    );
  },

  async down(queryInterface, Sequelize) {
    await queryInterface.bulkDelete("Productos", null, {});
  },
};
