"use strict";

/** @type {import('sequelize-cli').Migration} */
module.exports = {
  async up(queryInterface, Sequelize) {
    await queryInterface.bulkInsert(
      "Franelas",
      [
        {
          tela: "MICRODURAZNO",
          talla: "6",
          color: "BLANCA",
          cuello: "REDONDO",
          manga: "NORMAL",
          marca: "",
          stock: 3,
          precio: 0,
          observacion: "",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          tela: "MICRODURAZNO",
          talla: "8",
          color: "BLANCA",
          cuello: "REDONDO",
          manga: "NORMAL",
          marca: "",
          stock: 5,
          precio: 0,
          observacion: "",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          tela: "MICRODURAZNO",
          talla: "10",
          color: "BLANCA",
          cuello: "REDONDO",
          manga: "NORMAL",
          marca: "",
          stock: 2,
          precio: 0,
          observacion: "",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          tela: "MICRODURAZNO",
          talla: "12",
          color: "BLANCA",
          cuello: "REDONDO",
          manga: "NORMAL",
          marca: "",
          stock: 10,
          precio: 0,
          observacion: "",
          createdAt: new Date,
          updatedAt: new Date,
        },
        {
          tela: "MICRODURAZNO",
          talla: "14",
          color: "BLANCA",
          cuello: "REDONDO",
          manga: "NORMAL",
          marca: "",
          stock: 1,
          precio: 0,
          observacion: "",
          createdAt: new Date,
          updatedAt: new Date,
        },
        {
          tela: "MICRODURAZNO",
          talla: "16",
          color: "BLANCA",
          cuello: "REDONDO",
          manga: "NORMAL",
          marca: "",
          stock: 3,
          precio: 0,
          observacion: "",
          createdAt: new Date,
          updatedAt: new Date,
        },
        {
          tela: "MICRODURAZNO",
          talla: "1",
          color: "BLANCA",
          cuello: "REDONDO",
          manga: "NORMAL",
          marca: "",
          stock: 2,
          precio: 0,
          observacion: "",
          createdAt: new Date,
          updatedAt: new Date,
        },
        {
          tela: "MICRODURAZNO",
          talla: "6",
          color: "VERDE",
          cuello: "REDONDO",
          manga: "FARALADO",
          marca: "",
          stock: 1,
          precio: 0,
          observacion: "",
          createdAt: new Date,
          updatedAt: new Date,
        },
        {
          tela: "MICRODURAZNO",
          talla: "U",
          color: "BLANCA",
          cuello: "REDONDO",
          manga: "NORMAL",
          marca: "",
          stock: 1,
          precio: 0,
          observacion: "",
          createdAt: new Date,
          updatedAt: new Date,
        },
        {
          tela: "MICRODURAZNO",
          talla: "U",
          color: "BLANCA",
          cuello: "REDONDO",
          manga: "SISA LARGA",
          marca: "",
          stock: 2,
          precio: 0,
          observacion: "",
          createdAt: new Date,
          updatedAt: new Date,
        },
        {
          tela: "MICRODURAZNO",
          talla: "U",
          color: "BLANCA",
          cuello: "REDONDO",
          manga: "FARALADO",
          marca: "",
          stock: 4,
          precio: 0,
          observacion: "",
          createdAt: new Date,
          updatedAt: new Date,
        },
        {
          tela: "MICRODURAZNO",
          talla: "M",
          color: "BLANCA",
          cuello: "REDONDO",
          manga: "NORMAL",
          marca: "",
          stock: 6,
          precio: 0,
          observacion: "",
          createdAt: new Date,
          updatedAt: new Date,
        },
        {
          tela: "MICRODURAZNO",
          talla: "L",
          color: "BLANCA",
          cuello: "REDONDO",
          manga: "NORMAL",
          marca: "",
          stock: 3,
          precio: 0,
          observacion: "",
          createdAt: new Date,
          updatedAt: new Date,
        },
        {
          tela: "MICRODURAZNO",
          talla: "L",
          color: "BLANCA",
          cuello: "REDONDO",
          manga: "FARALADO",
          marca: "",
          stock: 2,
          precio: 0,
          observacion: "",
          createdAt: new Date,
          updatedAt: new Date,
        },
        {
          tela: "MICRODURAZNO",
          talla: "U",
          color: "ROSADA",
          cuello: "REDONDO",
          manga: "NORMAL",
          marca: "",
          stock: 3,
          precio: 0,
          observacion: "",
          createdAt: new Date,
          updatedAt: new Date,
        },
        {
          tela: "MICRODURAZNO",
          talla: "S",
          color: "BLANCA",
          cuello: "REDONDO",
          manga: "NORMAL",
          marca: "",
          stock: 4,
          precio: 0,
          observacion: "",
          createdAt: new Date,
          updatedAt: new Date,
        },
        {
          tela: "MICRODURAZNO",
          talla: "M",
          color: "BLANCA",
          cuello: "REDONDO",
          manga: "NORMAL",
          marca: "",
          stock: 1,
          precio: 0,
          observacion: "",
          createdAt: new Date,
          updatedAt: new Date,
        },
        {
          tela: "MICRODURAZNO",
          talla: "L",
          color: "BLANCA",
          cuello: "REDONDO",
          manga: "NORMAL",
          marca: "",
          stock: 2,
          precio: 0,
          observacion: "",
          createdAt: new Date,
          updatedAt: new Date,
        },
        {
          tela: "MICRODURAZNO",
          talla: "XL",
          color: "BLANCA",
          cuello: "REDONDO",
          manga: "NORMAL",
          marca: "",
          stock: 1,
          precio: 0,
          observacion: "",
          createdAt: new Date,
          updatedAt: new Date,
        },
        {
          tela: "MICRODURAZNO",
          talla: "2XL",
          color: "BLANCA",
          cuello: "REDONDO",
          manga: "NORMAL",
          marca: "",
          stock: 1,
          precio: 0,
          observacion: "",
          createdAt: new Date,
          updatedAt: new Date,
        },
        {
          tela: "MICRODURAZNO",
          talla: "3XL",
          color: "BLANCA",
          cuello: "REDONDO",
          manga: "NORMAL",
          marca: "",
          stock: 2,
          precio: 0,
          observacion: "",
          createdAt: new Date,
          updatedAt: new Date,
        },
        {
          tela: "MICRODURAZNO",
          talla: "XL",
          color: "NEGRO",
          cuello: "REDONDO",
          manga: "NORMAL",
          marca: "",
          stock: 1,
          precio: 0,
          observacion: "",
          createdAt: new Date,
          updatedAt: new Date,
        },
        {
          tela: "MICRODURAZNO",
          talla: "S",
          color: "NEGRO",
          cuello: "REDONDO",
          manga: "NORMAL",
          marca: "",
          stock: 2,
          precio: 0,
          observacion: "",
          createdAt: new Date,
          updatedAt: new Date,
        },
        {
          tela: "MICRODURAZNO",
          talla: "XL",
          color: "NEGRO",
          cuello: "V",
          manga: "NORMAL",
          marca: "",
          stock: 1,
          precio: 0,
          observacion: "",
          createdAt: new Date,
          updatedAt: new Date,
        },
        {
          tela: "MICRODURAZNO",
          talla: "M",
          color: "BLANCA",
          cuello: "REDONDO",
          manga: "LARGA",
          marca: "",
          stock: 1,
          precio: 0,
          observacion: "",
          createdAt: new Date,
          updatedAt: new Date,
        },
        {
          tela: "MICRODURAZNO",
          talla: "6",
          color: "TYDY",
          cuello: "REDONDO",
          manga: "NORMAL",
          marca: "",
          stock: 4,
          precio: 0,
          observacion: "",
          createdAt: new Date,
          updatedAt: new Date,
        },
        {
          tela: "MICRODURAZNO",
          talla: "U",
          color: "VARIADAS",
          cuello: "REDONDO",
          manga: "SISA LARGA",
          marca: "",
          stock: 4,
          precio: 0,
          observacion: "",
          createdAt: new Date,
          updatedAt: new Date,
        },
        {
          tela: "MICRODURAZNO",
          talla: "PLUS",
          color: "NEGRO",
          cuello: "S/MANGA",
          manga: "NORMAL",
          marca: "",
          stock: 1,
          precio: 0,
          observacion: "",
          createdAt: new Date,
          updatedAt: new Date,
        },
        {
          tela: "MICRODURAZNO",
          talla: "PLUS",
          color: "VERDE",
          cuello: "REDONDO",
          manga: "S/MANGA",
          marca: "",
          stock: 1,
          precio: 0,
          observacion: "",
          createdAt: new Date,
          updatedAt: new Date,
        },
        {
          tela: "MICRODURAZNO",
          talla: "S",
          color: "LILA",
          cuello: "REDONDO",
          manga: "NORMAL",
          marca: "",
          stock: 2,
          precio: 0,
          observacion: "",
          createdAt: new Date,
          updatedAt: new Date,
        },
        {
          tela: "MICRODURAZNO",
          talla: "U",
          color: "MORADA",
          cuello: "V",
          manga: "NORMAL",
          marca: "",
          stock: 1,
          precio: 0,
          observacion: "",
          createdAt: new Date,
          updatedAt: new Date,
        },
        {
          tela: "MICRODURAZNO",
          talla: "PLUS",
          color: "BEIGE",
          cuello: "REDONDO",
          manga: "NORMAL",
          marca: "",
          stock: 1,
          precio: 0,
          observacion: "",
          createdAt: new Date,
          updatedAt: new Date,
        },
        {
          tela: "MICRODURAZNO",
          talla: "PLUS",
          color: "MORADA",
          cuello: "REDONDO",
          manga: "NORMAL",
          marca: "",
          stock: 2,
          precio: 0,
          observacion: "",
          createdAt: new Date,
          updatedAt: new Date,
        },
        {
          tela: "MICRODURAZNO",
          talla: "PLUS RECTA",
          color: "NEGRO",
          cuello: "V",
          manga: "NORMAL",
          marca: "",
          stock: 2,
          precio: 0,
          observacion: "",
          createdAt: new Date,
          updatedAt: new Date,
        },
        {
          tela: "MICRODURAZNO",
          talla: "PLUS RECTA",
          color: "MORADA",
          cuello: "V",
          manga: "NORMAL",
          marca: "",
          stock: 1,
          precio: 0,
          observacion: "",
          createdAt: new Date,
          updatedAt: new Date,
        },
        {
          tela: "MICRODURAZNO",
          talla: "U",
          color: "AZUL",
          cuello: "V",
          manga: "NORMAL",
          marca: "",
          stock: 1,
          precio: 0,
          observacion: "",
          createdAt: new Date,
          updatedAt: new Date,
        },
        {
          tela: "MICRODURAZNO",
          talla: "U",
          color: "NEGRO",
          cuello: "V",
          manga: "NORMAL",
          marca: "",
          stock: 1,
          precio: 0,
          observacion: "",
          createdAt: new Date,
          updatedAt: new Date,
        },
        {
          tela: "MICRODURAZNO",
          talla: "U",
          color: "AMARILLO",
          cuello: "REDONDO",
          manga: "NORMAL",
          marca: "",
          stock: 1,
          precio: 0,
          observacion: "",
          createdAt: new Date,
          updatedAt: new Date,
        },
        {
          tela: "MICRODURAZNO",
          talla: "M",
          color: "TURQUESA",
          cuello: "REDONDO",
          manga: "FARALADO",
          marca: "",
          stock: 1,
          precio: 0,
          observacion: "",
          createdAt: new Date,
          updatedAt: new Date,
        },
        {
          tela: "MICRODURAZNO",
          talla: "U",
          color: "ROJO",
          cuello: "REDONDO",
          manga: "NORMAL",
          marca: "",
          stock: 2,
          precio: 0,
          observacion: "",
          createdAt: new Date,
          updatedAt: new Date,
        },
        {
          tela: "MICRODURAZNO",
          talla: "M",
          color: "GRIS",
          cuello: "REDONDO",
          manga: "NORMAL",
          marca: "",
          stock: 1,
          precio: 0,
          observacion: "",
          createdAt: new Date,
          updatedAt: new Date,
        },
        {
          tela: "ALGODON",
          talla: "0",
          color: "BLANCA",
          cuello: "",
          manga: "",
          marca: "KLASICO",
          stock: 1,
          precio: 0,
          observacion: "",
          createdAt: new Date,
          updatedAt: new Date,
        },
        {
          tela: "ALGODON",
          talla: "2",
          color: "BLANCA",
          cuello: "",
          manga: "",
          marca: "KLASICO",
          stock: 0,
          precio: 0,
          observacion: "",
          createdAt: new Date,
          updatedAt: new Date,
        },
        {
          tela: "ALGODON",
          talla: "4",
          color: "BLANCA",
          cuello: "",
          manga: "",
          marca: "KLASICO",
          stock: 0,
          precio: 0,
          observacion: "",
          createdAt: new Date,
          updatedAt: new Date,
        },
        {
          tela: "ALGODON",
          talla: "6",
          color: "BLANCA",
          cuello: "",
          manga: "",
          marca: "KLASICO",
          stock: 0,
          precio: 0,
          observacion: "",
          createdAt: new Date,
          updatedAt: new Date,
        },
        {
          tela: "ALGODON",
          talla: "8",
          color: "BLANCA",
          cuello: "",
          manga: "",
          marca: "KLASICO",
          stock: 0,
          precio: 0,
          observacion: "",
          createdAt: new Date,
          updatedAt: new Date,
        },
        {
          tela: "ALGODON",
          talla: "10",
          color: "BLANCA",
          cuello: "",
          manga: "",
          marca: "KLASICO",
          stock: 0,
          precio: 0,
          observacion: "",
          createdAt: new Date,
          updatedAt: new Date,
        },
        {
          tela: "ALGODON",
          talla: "12",
          color: "BLANCA",
          cuello: "",
          manga: "",
          marca: "KLASICO",
          stock: 0,
          precio: 0,
          observacion: "",
          createdAt: new Date,
          updatedAt: new Date,
        },
        {
          tela: "ALGODON",
          talla: "14",
          color: "BLANCA",
          cuello: "",
          manga: "",
          marca: "KLASICO",
          stock: 4,
          precio: 0,
          observacion: "",
          createdAt: new Date,
          updatedAt: new Date,
        },
        {
          tela: "ALGODON",
          talla: "16",
          color: "BLANCA",
          cuello: "",
          manga: "",
          marca: "KLASICO",
          stock: 4,
          precio: 0,
          observacion: "",
          createdAt: new Date,
          updatedAt: new Date,
        },
        {
          tela: "ALGODON",
          talla: "18",
          color: "BLANCA",
          cuello: "",
          manga: "",
          marca: "KLASICO",
          stock: 3,
          precio: 0,
          observacion: "",
          createdAt: new Date,
          updatedAt: new Date,
        },
        {
          tela: "ALGODON",
          talla: "S",
          color: "BLANCA",
          cuello: "",
          manga: "",
          marca: "KLASICO",
          stock: 2,
          precio: 0,
          observacion: "",
          createdAt: new Date,
          updatedAt: new Date,
        },
        {
          tela: "ALGODON",
          talla: "M",
          color: "BLANCA",
          cuello: "",
          manga: "",
          marca: "KLASICO",
          stock: 0,
          precio: 0,
          observacion: "",
          createdAt: new Date,
          updatedAt: new Date,
        },
        {
          tela: "ALGODON",
          talla: "L",
          color: "BLANCA",
          cuello: "",
          manga: "",
          marca: "KLASICO",
          stock: 3,
          precio: 0,
          observacion: "",
          createdAt: new Date,
          updatedAt: new Date,
        },
        {
          tela: "ALGODON",
          talla: "XL",
          color: "BLANCA",
          cuello: "",
          manga: "",
          marca: "KLASICO",
          stock: 3,
          precio: 0,
          observacion: "",
          createdAt: new Date,
          updatedAt: new Date,
        },
        {
          tela: "ALGODON",
          talla: "2XL",
          color: "BLANCA",
          cuello: "",
          manga: "",
          marca: "KLASICO",
          stock: 6,
          precio: 0,
          observacion: "",
          createdAt: new Date,
          updatedAt: new Date,
        },
        {
          tela: "ALGODON",
          talla: "3XL",
          color: "BLANCA",
          cuello: "",
          manga: "",
          marca: "KLASICO",
          stock: 5,
          precio: 0,
          observacion: "",
          createdAt: new Date,
          updatedAt: new Date,
        },
        {
          tela: "ALGODON",
          talla: "0",
          color: "NEGRO",
          cuello: "",
          manga: "",
          marca: "KLASICO",
          stock: 0,
          precio: 0,
          observacion: "",
          createdAt: new Date,
          updatedAt: new Date,
        },
        {
          tela: "ALGODON",
          talla: "2",
          color: "NEGRO",
          cuello: "",
          manga: "",
          marca: "KLASICO",
          stock: 0,
          precio: 0,
          observacion: "",
          createdAt: new Date,
          updatedAt: new Date,
        },
        {
          tela: "ALGODON",
          talla: "4",
          color: "NEGRO",
          cuello: "",
          manga: "",
          marca: "KLASICO",
          stock: 0,
          precio: 0,
          observacion: "",
          createdAt: new Date,
          updatedAt: new Date,
        },
      ],
      {}
    );
  },

  async down(queryInterface, Sequelize) {
    await queryInterface.bulkDelete("Franelas", null, {});
  },
};
